% Auto-generated by cameraCalibrator app on 18-Nov-2020
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/yuqiang/class/robotcs_HW3/DSC_0005.JPG',...
    '/home/yuqiang/class/robotcs_HW3/DSC_0006.JPG',...
    '/home/yuqiang/class/robotcs_HW3/DSC_0007.JPG',...
    '/home/yuqiang/class/robotcs_HW3/DSC_0008.JPG',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
for i=1:4
    originalImage = imread(imageFileNames{i});
    undistortedImage = undistortImage(originalImage, cameraParams);
    figure
    imshow(undistortedImage)
end
% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
